import { AcquirerEnum } from './enum/acquirer.enum';
import { WebhookReceivedStatusEnum } from './enum/webhook-received-status.enum';
import { StatusHistory } from './valiue-object/status-history.vo';
export declare class WebhookReceivedEntity {
    private readonly hash;
    private readonly tenant;
    private readonly acquirer;
    private readonly receivedAt;
    private readonly body;
    private updatedAt;
    private status;
    private error?;
    private statusHistory;
    static create(tenant: string, acquirer: AcquirerEnum, body: object): WebhookReceivedEntity;
    static restore(props: WebhookReceivedProperties): WebhookReceivedEntity;
    setError(errorMessage: string): void;
    setStatus(status: WebhookReceivedStatusEnum): void;
    getHash(): string;
    getTenant(): string;
    getAcquirer(): AcquirerEnum;
    getBody(): object;
    getReceivedAt(): Date;
    getUpdatedAt(): Date;
    getError(): string;
    getStatus(): WebhookReceivedStatusEnum;
    getStatusHistory(): StatusHistory[];
    private update;
    private constructor();
    private validate;
    private static generateHash;
}
export type WebhookReceivedProperties = {
    hash: string;
    body: object;
    tenant: string;
    acquirer: AcquirerEnum;
    receivedAt: Date;
    updatedAt?: Date;
    status?: WebhookReceivedStatusEnum;
    statusHistory?: StatusHistory[];
    error?: string;
};
