name: Publish Core Library

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com/'

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install --workspace=@splitwave-br/core

      - name: Build lib
        run: npm run build --workspace=@splitwave-br/core

      - name: Publish package
        run: npm publish --workspace=@splitwave-br/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}