name: Release Packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com/'

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Install dependencies
        run: npm install

      # Build na ordem correta
      - name: Build core
        run: npm run build --workspace=@splitwave-br/core

      - name: Build context-service
        run: npm run build --workspace=@splitwave-br/context-service

      - name: Build queue
        run: npm run build --workspace=@splitwave-br/queue

      - name: Build
